Strictly check configuration
criteo-forks/carbon-relay-ng pull request #23
Opened 2019-06-17 11:28 UTC by uepoch

One caveat with Inputs is that mapstructure does not allow to display a
proper name for each structure. To be addressed in a PR/Fork

2019-06-17 11:55 UTC, adriengentil requested changes

2019-06-17 11:55 UTC, adriengentil commented on cfg/input.go
> +	decoderErrorFmt  = "error while initializing the mapstructure deocoder: %s"
typo: decoder

2019-07-03 09:17 UTC, uepoch commented on cfg/input.go
> +	decoderErrorFmt  = "error while initializing the mapstructure deocoder: %s"
Done

2019-07-03 09:17 UTC, uepoch commented
cc @adriengentil

2019-07-03 09:22 UTC, adriengentil approved these changes

2019-07-04 10:04 UTC, merged